# Generated by Django 4.2 on 2024-07-04 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercred',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Email must be from aun.edu.ng domain.', regex='@aun\\.edu\\.ng$')]),
        ),
    ]
