# Generated by Django 4.2 on 2024-07-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resident',
            new_name='Residents',
        ),
        migrations.RenameModel(
            old_name='Role',
            new_name='Roles',
        ),
        migrations.RenameModel(
            old_name='Staff',
            new_name='Staffs',
        ),
    ]
