# Generated by Django 4.2 on 2024-07-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0002_rename_resident_residents_rename_role_roles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
    ]
