# Generated by Django 4.2 on 2024-08-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0003_remove_residents_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residents',
            old_name='guardianPhoneNumber',
            new_name='guardian_phone_number',
        ),
        migrations.RenameField(
            model_name='usercred',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
