# Generated by Django 4.2 on 2024-07-04 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0003_role_alter_usercred_email_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usercred',
            name='email',
            field=models.EmailField(default='aun@example.com', max_length=255, validators=[django.core.validators.RegexValidator(message='Email must be from aun.edu.ng domain.', regex='@aun\\.edu\\.ng$')]),
        ),
    ]
