# Generated by Django 4.2 on 2024-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0004_remove_role_description_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
