# Generated by Django 4.2 on 2024-08-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('UserProfiles', '0004_rename_guardianphonenumber_residents_guardian_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
