# Generated by Django 4.2 on 2024-09-18 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0005_roles_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residents',
            options={'ordering': ['user__username'], 'verbose_name': 'resident', 'verbose_name_plural': 'residents'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['name'], 'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='staffs',
            options={'ordering': ['user__username'], 'verbose_name': 'staff', 'verbose_name_plural': 'staffs'},
        ),
        migrations.AlterModelOptions(
            name='usercred',
            options={'ordering': ['username'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='usercred',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.RegexValidator(message='Email must be from aun.edu.ng domain.', regex='@aun\\.edu\\.ng$')]),
        ),
    ]
