# Generated by Django 4.2 on 2024-09-18 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0006_alter_residents_options_alter_roles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercred',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Email must be from aun.edu.ng domain.', regex='@aun\\.edu\\.ng$')]),
        ),
        migrations.AlterField(
            model_name='usercred',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
