# Generated by Django 4.2 on 2024-09-26 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0009_alter_usercred_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercred',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
