# Generated by Django 4.2 on 2024-09-26 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0010_usercred_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
