# Generated by Django 4.2 on 2024-09-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0011_staffs_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='residents',
            name='address',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
