# Generated by Django 4.2 on 2024-09-30 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0012_residents_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercred',
            options={},
        ),
        migrations.AddField(
            model_name='residents',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='UserProfiles.roles'),
        ),
        migrations.AlterField(
            model_name='usercred',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
