# Generated by Django 4.2 on 2024-10-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0013_alter_usercred_options_residents_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['my_order'], 'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AddField(
            model_name='roles',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
