# Generated by Django 4.2 on 2024-11-20 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0015_alter_residents_user_alter_staffs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfiles.roles'),
        ),
    ]
