# Generated by Django 4.2 on 2024-07-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('name', models.CharField(blank=True, editable=False, help_text='Automatically formatted as start_year/end_year', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_type', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicYear.academicsession')),
            ],
        ),
    ]
