# Generated by Django 4.2 on 2024-07-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dorms', '0001_initial'),
        ('UserProfiles', '0001_initial'),
        ('AcademicYear', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfiles.roles'),
        ),
        migrations.AddField(
            model_name='staffassignment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicYear.semester'),
        ),
        migrations.AddField(
            model_name='staffassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfiles.staffs'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicYear.academicsession'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='AcademicYear.academicsession'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Dorms.dorm'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='UserProfiles.residents'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Dorms.room'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='AcademicYear.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='staffassignment',
            unique_together={('staff', 'dorm', 'academic_session', 'semester')},
        ),
    ]
