# Generated by Django 4.2 on 2024-07-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicYear', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'verbose_name': 'Academic Session', 'verbose_name_plural': 'Academic Sessions'},
        ),
    ]
