# Generated by Django 4.2 on 2024-09-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicYear', '0005_academicsession_created_at_enrollment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Intersession', 'Intersession')], max_length=20),
        ),
    ]
