# Generated by Django 4.2 on 2024-11-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicYear', '0006_alter_semester_semester_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=10),
        ),
    ]
