# Generated by Django 4.2 on 2024-11-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0016_alter_residents_role'),
        ('AcademicYear', '0007_enrollment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('resident', 'semester', 'academic_session')},
        ),
    ]
