# Generated by Django 4.2 on 2024-11-22 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0016_alter_residents_role'),
        ('AcademicYear', '0008_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffassignments', to='UserProfiles.staffs'),
        ),
    ]
