# Generated by Django 4.2 on 2024-07-13 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicYear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'Unisex')], default='M', max_length=1)),
                ('campus_status', models.CharField(choices=[('ON', 'On Campus'), ('OFF', 'Off Campus')], default='ON', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('room_plan', models.CharField(choices=[('3_in_1_wof', 'Triple Without Facilities'), ('2_in_1_wof', 'Double Without Facilities'), ('3_in_1_wf', 'Triple With Facilities'), ('2_in_1_wf', 'Double With Facilities')], max_length=20)),
                ('floor', models.IntegerField(choices=[(1, 'Ground Floor'), (2, 'First Floor'), (3, 'Second Floor'), (4, 'Third Floor')])),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('floor', models.IntegerField(choices=[(1, 'Ground Floor'), (2, 'First Floor'), (3, 'Second Floor'), (4, 'Third Floor')])),
                ('current_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='AcademicYear.academicsession')),
            ],
        ),
    ]
