# Generated by Django 4.2 on 2024-07-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicYear', '0003_initial'),
        ('Dorms', '0001_initial'),
        ('UserProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_storage_items', to='UserProfiles.staffs'),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_items', to='UserProfiles.residents'),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='UserProfiles.residents'),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Dorms.room'),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='AcademicYear.semester'),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Dorms.storage'),
        ),
        migrations.AddField(
            model_name='storage',
            name='dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='Dorms.dorm'),
        ),
        migrations.AddField(
            model_name='room',
            name='dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Dorms.dorm'),
        ),
    ]
