# Generated by Django 4.2 on 2024-07-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dorms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dorms',
            new_name='Dorm',
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='Storages',
            new_name='Storage',
        ),
        migrations.RenameModel(
            old_name='StorageItems',
            new_name='StorageItem',
        ),
    ]
