# Generated by Django 4.2 on 2024-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dorms', '0002_rename_dorms_dorm_rename_rooms_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
