# Generated by Django 4.2 on 2024-07-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dorms', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Storage Location', 'verbose_name_plural': 'Storage Locations'},
        ),
        migrations.AlterModelOptions(
            name='storageitem',
            options={'verbose_name': 'Storage Item', 'verbose_name_plural': 'Storage Items'},
        ),
    ]
