# Generated by Django 4.2 on 2024-08-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dorms', '0003_alter_storage_options_alter_storageitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='range',
            field=models.CharField(blank=True, choices=[('101-116', '101-116'), ('201-216', '201-216'), ('301-316', '301-316'), ('2x2a-2x2b', '2x2a-2x2b'), ('3x3a-3x3b', '3x3a-3x3b')], max_length=20, null=True),
        ),
    ]
