# Generated by Django 4.2 on 2024-07-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dorms', '0003_alter_dorm_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
