# Generated by Django 4.2 on 2024-07-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dorms', '0004_alter_dorm_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
