# Generated by Django 4.2 on 2024-07-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dorms', '0005_alter_dorm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='capacity',
            field=models.IntegerField(default=0, help_text='Total capacity of the dorm'),
        ),
    ]
