# Generated by Django 4.2 on 2024-08-17 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dorms', '0005_alter_room_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
