# Generated by Django 4.2 on 2024-11-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dorms', '0007_room_is_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='dorms_set', to='Dorms.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_set', to='Dorms.dorm'),
        ),
    ]
