# Generated by Django 4.2 on 2024-11-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dorms', '0008_dorm_rooms_alter_room_dorm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorm',
            name='rooms',
        ),
        migrations.AlterField(
            model_name='room',
            name='dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Dorms.dorm'),
        ),
    ]
