# Generated by Django 4.2 on 2024-07-13 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfiles', '0001_initial'),
        ('Dorms', '0001_initial'),
        ('Actions', '0002_initial'),
        ('AcademicYear', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='UserProfiles.residents'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='Dorms.room'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='AcademicYear.semester'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actions.subcategory'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_requests', to='UserProfiles.staffs'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='AcademicYear.academicsession'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='AcademicYear.enrollment'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='AcademicYear.semester'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='AcademicYear.academicsession'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to='UserProfiles.staffs'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='dorms',
            field=models.ManyToManyField(blank=True, to='Dorms.dorm'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='AcademicYear.semester'),
        ),
    ]
