# Generated by Django 4.2 on 2024-07-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Maintenance-Category', 'verbose_name_plural': 'Maintenance-Categories'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'verbose_name': 'Maintenance Request', 'verbose_name_plural': 'Maintenance Requests'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Maintenance-Sub-Category', 'verbose_name_plural': 'Maintenance-Sub-Categories'},
        ),
    ]
