# Generated by Django 4.2 on 2024-10-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0005_complaint_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('wifi', 'Wi-Fi'), ('television', 'Television'), ('noise', 'Noise Complaint'), ('fight', 'Physical Abuse'), ('sex', 'Sexual Abuse'), ('drug', 'Drugs'), ('residence staff', 'Residence Staffs'), ('cleaners', 'Cleaning Staffs')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
