# Generated by Django 4.2 on 2024-11-06 22:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Dorms', '0007_room_is_occupied'),
        ('Actions', '0006_category_my_order_complaint_complaint_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_off_campus', models.BooleanField(default=False)),
                ('product', models.CharField(max_length=200)),
                ('dorm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='Dorms.dorm')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
    ]
