# Generated by Django 4.2 on 2024-11-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dorms', '0009_remove_dorm_rooms_alter_room_dorm'),
        ('Actions', '0008_complaint_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='dorms',
            field=models.ManyToManyField(blank=True, help_text='Select dorms for the announcement (Leave blank for global announcements).', to='Dorms.dorm'),
        ),
    ]
